### ISSUE TITLE
"set_property can not be used on an ALIAS target" error for dawn-6420

### ISSUE THREAD

**Issue by austinvhuang** [eliemichel/WebGPU-distribution#16]
When I build with `dawn-6420` as the GIT_TAG for FetchContent, I get this error:

```
CMake Error at build/_deps/webgpu-backend-dawn-src/cmake/FetchDawn.cmake:157 (set_property):
  set_property can not be used on an ALIAS target.
Call Stack (most recent call first):
  build/_deps/webgpu-backend-dawn-src/CMakeLists.txt:23 (include)
```
When I revert to `dawn-6376`, this no longer occurs

**Comment by eliemichel** [comment]
Hello! If you want to update to a newer version of Dawn, start from the current head of the `dawn` branch which is more up to date than what the stable version of `webgpu.cmake` points to (which is updated less often to reduce breaking changes).

You can see in the newer [`FetchDawn.cmake`](https://github.com/eliemichel/WebGPU-distribution/blob/dawn/cmake/FetchDawn.cmake#L193) that the call to `set_property` is enclosed in a test to prevent exactly the error you're running into. ;)
