### ISSUE TITLE
Problem with 32-bit build on Windows

### ISSUE THREAD

**Issue by MikhailGorobets** [eliemichel/WebGPU-distribution#19]
This section of the code does not specify the selection of 32-bit DLLs. I also suggest not modifying the `ARCH` variable.
https://github.com/eliemichel/WebGPU-distribution/blob/ac055bef9d8c37f28e7706e4bd32153cbc0c210f/CMakeLists.txt#L27
For exampe we can rewrite this section like this:
```cmake
set(SYSTEM_PROCESSOR ${CMAKE_SYSTEM_PROCESSOR})
if (SYSTEM_PROCESSOR STREQUAL "AMD64" OR SYSTEM_PROCESSOR STREQUAL "x86_64")
    if(CMAKE_SIZEOF_VOID_P EQUAL 8)
        set(ARCH "x86_64")
    endif()

    if(CMAKE_SIZEOF_VOID_P EQUAL 4)
        set(ARCH "i686")
    endif()
endif()

if (SYSTEM_PROCESSOR STREQUAL "arm64")
    set(ARCH "aarch64")
endif()    
```

**Comment by eliemichel** [comment]
Thanks for the suggestion! Indeed I missed the fact that `CMAKE_SYSTEM_PROCESSOR` is nicely designed to correspond to the target architecture only "in many cases [...], but this is not guaranteed" ([source](https://cmake.org/cmake/help/latest/variable/CMAKE_SYSTEM_PROCESSOR.html)).

I upgraded the `wgpu` and `wgpu-static` branches to reflect that!
