### ISSUE TITLE
libprotobuf-mutator fails to build when using WEBGPU_BACKEND=DAWN

### ISSUE THREAD

**Issue by jpvanoosten** [eliemichel/WebGPU-distribution#20]
The `libprotobuf-mutator` library fails to build when using `WEBGPU_BACKEND=DAWN` since it seems to be missing the google/protobuff library dependency when compiling on Windows (Visual Studio 2022). I did not try other platforms.

This is not an issue since it doesn't seem that anything depends on `libprotobuf-mutator` so perhaps this target can be disabled or deleted?

**Comment by eliemichel** [comment]
Upgraded in WebGPU-distribution's `main` as well as all branches of LearnWerbGPU-Code that used that version of the distribution.

**Comment by eliemichel** [comment]
Woops, what did I do, thanks!
