### ISSUE TITLE
dawn-6536: Wrong chromium version fetched

### ISSUE THREAD

**Issue by aaeberharter** [eliemichel/WebGPU-distribution#25]
[Branch dawn-6536](https://github.com/eliemichel/WebGPU-distribution/tree/dawn-6536) fetches the wrong dawn version, causing a mismatch between `webgpu.h` and `webgpu.hpp`.

https://github.com/eliemichel/WebGPU-distribution/blob/acf972b7b909f52e183bdae3971b93bb13d4a29e/cmake/FetchDawn.cmake#L42

I recommend upgrading it to `6536`

**Comment by eliemichel** [comment]
Fixed the tag, thanks for noticing and reporting this!
