### ISSUE TITLE
Prefer to use FETCHCONTENT_BASE_DIR when specifying include directories from FetchContent (Dawn)

### ISSUE THREAD

**Issue by NoctemCat** [eliemichel/WebGPU-distribution#35]
This variable controls the point under which all content population directories are collected, also when not changed it points to it. If it was changed `target_include_directories` would now include nonexistent directory.

Now that I looked at it, `${dawn_SOURCE_DIR}` was also defined. Either of them would work

**Comment by NoctemCat** [comment]
This one 
![image](https://github.com/user-attachments/assets/39e1896a-f898-491f-8c13-99ae49aaf132)

**Comment by eliemichel** [comment]
Good catch, thanks! Fixed by [35bad0c](https://github.com/eliemichel/WebGPU-distribution/commit/35bad0c27e94c10a77e93974640a51792317a11f)
