### ISSUE TITLE
[dawn] `markupsafe` dependency missing

### ISSUE THREAD

**Issue by dannymcgee** [eliemichel/WebGPU-distribution#5]
Thanks for putting this together! I gave wgpu a spin in Rust years ago and liked it a lot, but have been trying to improve my C++ chops recently and wanted to give Dawn a try. I gave up pretty quickly after running into dependency issues that were over my head, but then I came across [your guide](https://eliemichel.github.io/LearnWebGPU) and decided to give it another go.

I did run into one issue when trying to configure CMake with the Dawn backend — it complained that `markupsafe` couldn't be found. After a bit of poking around I found that adding `'third_party/markupsafe'` to the fetch script's `required_submodules` array fixed the issue. I have no idea how to Python, but I'm opening a naive PR with that change on the off chance that's really all there is to it. :)

**Comment by eliemichel** [comment]
Thanks for the PR! This is a new dependency of Dawn indeed, your fix is correct :)
