### ISSUE TITLE
Compiling `dawn` error: set_property could not find TARGET update_mappings

### ISSUE THREAD

**Issue by rollschild** [eliemichel/WebGPU-distribution#7]
Hi,

First of all thanks for this cool project! I've been following the [Learn WebGPU](https://eliemichel.github.io/LearnWebGPU/index.html), although it's still WIP it's been very useful so far! And I'm amazed by how quickly bugs got fixed. Previously I ran into the [`markupsafe` missing](https://github.com/eliemichel/WebGPU-distribution/issues/5) error but I noticed that it had been already fixed.

I'm seeing another error right now while compiling `dawn` on Linux (NixOS) for Wayland:
```
CMake Error at webgpu/cmake/FetchDawn.cmake:77 (set_property):
  set_property could not find TARGET update_mappings.  Perhaps it has not yet
  been created.
Call Stack (most recent call first):
  webgpu/CMakeLists.txt:21 (make_dawn_available)
```
I see that it was due to `	set_property(TARGET update_mappings PROPERTY FOLDER "External/GLFW3")
` in `webgpu/cmake/FetchDawn.cmake` but I'm not sure how to fix it. Could you please help? Thanks!

**Comment by eliemichel** [comment]
Okey I guess we can wrap this in some `if (TARGET update_mappings)` because the existence of the target may depend on the OS!

**Comment by rollschild** [comment]
@eliemichel Thanks for the tip! Build succeeded. Ran into another error at run time. Not sure if it's me or something else. I will open another issue if I couldn't figure it out myself.

**Comment by rollschild** [comment]
Well, during `cmake . -B build`, I saw the following log:
```
-- Dawn build Wayland support: OFF
-- Dawn build X11 support: ON
```
Does it mean wayland support for Dawn is turned off?

**Comment by eliemichel** [comment]
Did you check whether other vulkan-based program run correctly on your system?

**Comment by rollschild** [comment]
@eliemichel You are right. I pulled in some vulkan dependencies and now it's working. Instance created. Surface created. Adapter requested with non-zero value. There are only two warnings, which I think are probably fine.
```
Warning: terminator_CreateInstance: Failed to CreateInstance in ICD 0.  Skipping ICD.
Warning: terminator_CreateInstance: Failed to CreateInstance in ICD 3.  Skipping ICD.
```

And these are the Adapter features logged:
```
Adapter features:
 - 5
 - 6
 - 7
 - 4
 - 3
 - 1006
 - 1
 - 2
 - 1005
 - 8
 - 10
 - 11
 - 1002
 - 1004
 - 1007
```

**Comment by eliemichel** [comment]
Nice :) For the record, can you give some details about "pulling in some vulkan dependencies"? Anything worth sharing to other people in a similar situation that I could add to the guide?

**Comment by rollschild** [comment]
@eliemichel Sure. I'm using NixOS and this is a [flake](https://nixos.wiki/wiki/Flakes)-based project. My `flake.nix` is [here](https://github.com/rollschild/webgpu-cpp/blob/wgpu/flake.nix). Basically it pins any dependencies that are needed for the particular project.

The Vulkan dependencies that I added are:
```
            # vulkan 
            glslang # or shaderc
            vulkan-headers
            vulkan-loader
            vulkan-validation-layers # maybe?
            vulkan-tools
```

(Note: there are definitely unnecessary dependencies in my `flake.nix` but this is what works for me for now.)
